// mutation-types.ts:
export enum MutationTypes {
  SET_USERINFO = "SET_USERINFO",
  CLEAR_USERINFO = "CLEAR_USERINFO",
  GET_USERINFO = "GET_USERINFO",
  SET_GAME = "SET_GAME",
  CLEAR_GAME = "CLEAR_GAME",
  SET_WS = "SET_WS",
  CLEAR_WS = "CLEAR_WS",
  PUSH_MSG = "PUSH_MSG",
  CLEAR_MSG = "CLEAR_MSG",
  SET_EQUIP = "SET_EQUIP"
}
