ls: 
    src/*:
        .js: kebab-case | PascalCase
        .vue: PascalCase | regex:^index
        .ts: camelCase | PascalCase
        .d.ts: kebab-case
        .mock.ts: kebab-case
        .data.ts: camelCase | kebab-case
        .test-d.ts: kebab-case
        .scss: kebab-case | PascalCase
        .spec.ts: camelCase | PascalCase
        .dir: kebab-case
    
    src/store/*:
        .ts: kebab-case | PascalCase

    src/{api,const,hooks,layouts,page,router,types,utils}/*:
        .dir: PascalCase

    src/views/{layouts,sw,ow}/*:
        .dir: PascalCase

    src/views/ed/{customers,home}/*:
        .dir: PascalCase

    src/{api,const,hooks,router}/*:
        .ts: camelCase
        .js: camelCase

    src/components/*:
        .dir: PascalCase
        .ts: PascalCase
        .js: PascalCase
        .vue: PascalCase | regex:^index

ignore:
    - node_modules
    - .git
    - .circleci
    - .github
    - .vscode
    - dist
    - .local